//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Estudios_G7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD
    {
        public int id_Actividad { get; set; }
        public int tipo { get; set; }
        public int id_evento { get; set; }
        public int curso { get; set; }
    
        public virtual CURSO CURSO1 { get; set; }
    }
}
