//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Estudios_G7.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class EXAMan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAMan()
        {
            this.NOTA_EXAMEN = new HashSet<NOTA_EXAMEN>();
            this.RES_EXAMEN = new HashSet<RES_EXAMEN>();
        }
    
        public int id_examen { get; set; }
        [Required]
        [Display(Name = "Preguntas")]
        
        public string preguntas { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha")]
        //[Range(typeof(DateTime), "1/1/2019","31/12/2200",ErrorMessage ="Ingrese una fecha valida")]
        //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha { get; set; }
        [Required]
        [Display(Name = "Cantidad de Minutos")]
        [Range(1,200,ErrorMessage ="Numero de minutos entre 1 y 200")]
        public int minutos { get; set; }
        [Required]
        [Display(Name = "Curso")]
        public int curso { get; set; }

        public virtual CURSO CURSO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTA_EXAMEN> NOTA_EXAMEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RES_EXAMEN> RES_EXAMEN { get; set; }
    }
}
