//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Estudios_G7.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Sistema_estudiosEntities : DbContext
    {
        public Sistema_estudiosEntities()
            : base("name=Sistema_estudiosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CURSO> CURSOes { get; set; }
        public virtual DbSet<EXAMan> EXAMEN { get; set; }
        public virtual DbSet<NOTA_EXAMEN> NOTA_EXAMEN { get; set; }
        public virtual DbSet<NOTA_TAREA> NOTA_TAREA { get; set; }
        public virtual DbSet<TAREA> TAREAs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<ACTIVIDAD> ACTIVIDADs { get; set; }
        public virtual DbSet<COMENTARIO> COMENTARIOs { get; set; }
        public virtual DbSet<PUBLICACION> PUBLICACIONs { get; set; }
        public virtual DbSet<RES_EXAMEN> RES_EXAMEN { get; set; }
    
        public virtual ObjectResult<string> BUSCAR_USUARIOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BUSCAR_USUARIOS");
        }
    
        public virtual int NUEVO_USER(string nuevo_Nick, string nuevo_contra, string nuevo_nombre_1, string nuevo_nombre_2, string nuevo_apellido_1, string nuevo_apellido_2, Nullable<int> nuevo_edad, string nuevo_correo)
        {
            var nuevo_NickParameter = nuevo_Nick != null ?
                new ObjectParameter("Nuevo_Nick", nuevo_Nick) :
                new ObjectParameter("Nuevo_Nick", typeof(string));
    
            var nuevo_contraParameter = nuevo_contra != null ?
                new ObjectParameter("Nuevo_contra", nuevo_contra) :
                new ObjectParameter("Nuevo_contra", typeof(string));
    
            var nuevo_nombre_1Parameter = nuevo_nombre_1 != null ?
                new ObjectParameter("Nuevo_nombre_1", nuevo_nombre_1) :
                new ObjectParameter("Nuevo_nombre_1", typeof(string));
    
            var nuevo_nombre_2Parameter = nuevo_nombre_2 != null ?
                new ObjectParameter("Nuevo_nombre_2", nuevo_nombre_2) :
                new ObjectParameter("Nuevo_nombre_2", typeof(string));
    
            var nuevo_apellido_1Parameter = nuevo_apellido_1 != null ?
                new ObjectParameter("Nuevo_apellido_1", nuevo_apellido_1) :
                new ObjectParameter("Nuevo_apellido_1", typeof(string));
    
            var nuevo_apellido_2Parameter = nuevo_apellido_2 != null ?
                new ObjectParameter("Nuevo_apellido_2", nuevo_apellido_2) :
                new ObjectParameter("Nuevo_apellido_2", typeof(string));
    
            var nuevo_edadParameter = nuevo_edad.HasValue ?
                new ObjectParameter("Nuevo_edad", nuevo_edad) :
                new ObjectParameter("Nuevo_edad", typeof(int));
    
            var nuevo_correoParameter = nuevo_correo != null ?
                new ObjectParameter("Nuevo_correo", nuevo_correo) :
                new ObjectParameter("Nuevo_correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NUEVO_USER", nuevo_NickParameter, nuevo_contraParameter, nuevo_nombre_1Parameter, nuevo_nombre_2Parameter, nuevo_apellido_1Parameter, nuevo_apellido_2Parameter, nuevo_edadParameter, nuevo_correoParameter);
        }
    }
}
