//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Estudios_G7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_EXAMEN
    {
        public int estudiante { get; set; }
        public int examen { get; set; }
        public int nota { get; set; }
    
        public virtual EXAMan EXAMan { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
